version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NAME=.ENV
    volumes:
      - .:/app
    command: npm start
